### ISSUE TITLE
Ask for the order of regions in pre-calculated structural connectivity matrix

### ISSUE THREAD

**Issue by hitrp** [sina-mansour/UKB-connectomics#41]
Dear Sina, 

Thanks for the great contribution to the community, I am exploring the four pre-calculated structural connectivity matrices available in UKBiobank, but I couldn't find the corresponding order of regions, am I missing something? 

Best wishes,
Peng

**Comment by Lestropie** [comment]
It's common to desire a lookup table that has direct correspondence with matrix data being interrogated. This may be necessary for eg. visualisation if one wants to embed the data in a visual space or show parcel labels in the x-axis or y-axis ticks. Indeed in *MRtrix3* I [deliberately designed](https://mrtrix.readthedocs.io/en/3.0.4/quantitative_structural_connectivity/labelconvert_tutorial.html) the sequence of processing steps so that there would be correspondence between the contents of a lookup table and the rows / columns of the generated matrix. So pre-calculating and distributing lookup tables for the pre-generated matrices may be a reasonable idea.

Indeed in the usage scenario where users generate their own matrices from flexible selections of cortical & subcortical parcellations, the capability to concatenate the corresponding lookup tables in the same order as what is done to the parcel label image data might be of utility also. But would be a bit more effort than just doing the seven pre-calculated configurations manually.

**Comment by sina-mansour** [comment]
Yes indeed, I can see the utility of such a script. Alright then, I'll reopen this issue for now and this to my to-do list. I will probably write a short script that generates lookup tables for combined (cortical + subcortical) parcellation schemes. I will also include the combined lookup tables for our particular selections of pre-computed SC matrices for the sake of simplicity.
